### ISSUE TITLE
Reconnect on disconnect

### ISSUE THREAD

**Issue by domenkozar** [Tennu/tennu#34]
If for some reason the client gets disconnected, it does not reconnect to the server, which is a bit annoying :)

**Comment by Havvy** [comment]
Given all the state in a Tennu connection, automatic reconnection is a lot of work that would be extremely complex, and I don't want to reimplement half of OTP (see: Erlang) when it's possible to add `.on("quit", function () { tennu.Client(...).connect();}` (though with more checks and whatnot).
