### ISSUE TITLE
tennu appears to be closing IRC socket for no reason

### ISSUE THREAD

**Issue by alienth** [Tennu/tennu#47]
I have a fairly simple IRC bot which uses tennu. It is persistently connected to freenode. Once or twice a day it becomes disconnected from freenode. I have full debug logs enabled and there is nothing indicating why the disconnection occurred. I've also tcpdumped the traffic, and the client appears to cleanly close the socket, with no other activity immediately preceding the close (nor is there an unusual cessation of activity prior to the close).

I have a feeling I'm missing something. How might I go about debugging this further?

**Comment by Havvy** [comment]
I'm not sure why that would happen unless you're using one of the versions of `irc-socket` with poor timeout handling. Actually, it's still somewhat poor (though you say there's no unusual cessation of activity, so the current poor handling won't close in that case).

What version of `irc-socket` are you using?  Check with `npm ls`. If it's not v.2.3.2, you need to update.

If you want to catch timeouts when they happen, try adding this line somewhere.

`client.socket.on("timeout", function () { client.error("Socket timed out."); });`

**Comment by alienth** [comment]
I'm on 2.3.2. Will try catching the timeout and will letcha know. Thanks!

**Comment by Havvy** [comment]
Did you ever find anything?

**Comment by alienth** [comment]
It was indeed a socket timeout. Sorry for not updating the ticket! I'm guessing that irc-socket simply isn't retrying properly.
