### ISSUE TITLE
Cant login to pvpgn server

### ISSUE THREAD

**Issue by anonprophet** [Tennu/tennu#53]
i just use examples echobot.js

but the bot cant login

this is my config
```
{
    "server": "49.128.182.218",
    "port": 9999,
    "nicknames": ["tennu"],
    "username": "tennu",
    "realname": "tennu",
    "password": "123123",

    "plugins": [],
    "command-trigger": "!",

    "channels": ["#dev"],
    "nickserv": "nickserv",
    "auth-password": null,

    "tls": false
}
```
here if use node-irc and work
```
var irc = require('irc');

var client = new irc.Client('49.128.182.218', 'TENNU', {
	debug	: true,
	port	: 9999,
	password: '123123',
	channels: ['#dev']
})
```

whats wrong ?

**Comment by anonprophet** [comment]
@Havvy please help me

**Comment by Havvy** [comment]
I cannot connect to the network at all with any client. If you run the `tennu` command with `-v`, what does it say?

**Comment by anonprophet** [comment]
yes, bcoz my friend only allow from several IP
include my VPS

``tennu: command not found``

btw, i run tennu.js using `nodejs` command on ubuntu

**Comment by anonprophet** [comment]
any news @Havvy ?
or maybe i will give u access my VPS ?

**Comment by Havvy** [comment]
Closing unless still relevant?
