### ISSUE TITLE
Please add support for gamesurge.

### ISSUE THREAD

**Issue by LordWingZero** [Tennu/tennu#57]
Gamesurge doesn't respond to `CAP LS`
Gamesurge will probably have to be an IRCd type.

**Comment by jonnybot0** [comment]
+1

**Comment by step1step2** [comment]
:+1:

**Comment by LordWingZero** [comment]
It appears that Tennu doesnt work on Quakenet or Undernet, all three different networks have in common is they all use the IRCu daemon. Im sure there are plenty more.

**Comment by Havvy** [comment]
Added a daemon type of "irc2" that only uses irc2 versions. In v4.3.3. Though if you have `null` in your config file, either remove it or wait until v4.3.4 in a few minutes.
