### ISSUE TITLE
Ability to pass in verbose and debug as configuration options.

### ISSUE THREAD

**Issue by LordWingZero** [Tennu/tennu#58]
Currently to enable verbosity or debug mode they must be done as flags through the tennu binary.

I would like to have "verbose":true in my config.

**Comment by Havvy** [comment]
In case anybody looks at this in the future - If you're not using the "binary" provided with the library, you're passing in a logger on your own, and from that logger you get to decide how to handle each level of messages. There's no such thing as verbose logging as a concept in the Tennu library itself - just debug level logging.

**Comment by LordWingZero** [comment]
Yes I closed it after studying the binary and discovering this.
