### ISSUE TITLE
'nick' handler does not return the channel

### ISSUE THREAD

**Issue by LordWingZero** [Tennu/tennu#64]
Tennu doesn't seem to send back the channel in which it saw the nick change happen.

IRC Server: IRCu
Daemon: irc2

```Javascript
Message {
  command: 'nick',
  hostmask: 
   { nickname: 'text22',
     username: 'kiwiirc',
     hostname: '46d1fb7a.57077d0f.857a7d72.IP4' },
  nickname: 'text22',
  old: 'text22',
  new: 'abc123_1' }
```

**Comment by Havvy** [comment]
That's because nick changes are server level. The channel plugin /could/ do this, but the one in Tennu doesn't work with IRCu.
