### ISSUE TITLE
`kick` doesnt have reason on IRCu.

### ISSUE THREAD

**Issue by LordWingZero** [Tennu/tennu#65]
On gamesurge my kick message to my handler looked like this:

```Javascript
IRCMessage {
  command: 'kick',
  hostmask: 
   { nickname: 'TEST1',
     username: 'TEST123',
     hostname: 'TEST123.linux.gamesurge' },
  nickname: 'TEST1',
  channel: '#testchannel',
  kicked: 'test_user_123',
  kicker: 'an example kick reason' }
```

It should have a property called reason === 'an example kick reason' and kicker should be the nickname.

**Comment by Havvy** [comment]
Fixed in the v4.5 branch; will release after getting some channel plugin tests in there too.
