### ISSUE TITLE
Command Plugin Middleware

### ISSUE THREAD

**Issue by Havvy** [Tennu/tennu#67]
For things like the admin plugin, a potential roles plugin that supersedes the admin plugin, and @LordWingZero's plugin whose name escapes me right now.

**Comment by LordWingZero** [comment]
https://github.com/LordWingZero/tennu-cooldown

Right now, you can see the amount of code needed by a plugin that wanted to use tennu-cooldown as an optional dependency.

**Comment by LordWingZero** [comment]
Middleware feature added.
