### ISSUE TITLE
Registration timeout on InspIRCd-2.0.20

### ISSUE THREAD

**Issue by tomhatzer** [Tennu/tennu#68]
Just tried to connect my InspIRCd Server and could not pass registration.

Log:
> ~/tennu$ ./node_modules/.bin/tennu configs/config.json -v
> Connecting to 10.0.0.5:6667.
> Sat Nov 21 2015 14:06:17 GMT+0100 (CET) notice Tennu Loading base plugins
> Sat Nov 21 2015 14:06:18 GMT+0100 (CET) notice Tennu Subscriber 'action:' registered for plugin 'action'.
> Sat Nov 21 2015 14:06:18 GMT+0100 (CET) notice Tennu Subscriber '(no-prefix)' registered for plugin 'messages'.
> Sat Nov 21 2015 14:06:18 GMT+0100 (CET) notice Tennu Subscriber 'ctcp:' registered for plugin 'ctcp'.
> Sat Nov 21 2015 14:06:18 GMT+0100 (CET) notice Tennu Subscriber '!' registered for plugin 'commands'.
> Sat Nov 21 2015 14:06:18 GMT+0100 (CET) notice PluginCommands Registering 'help:help'.
> Sat Nov 21 2015 14:06:18 GMT+0100 (CET) notice PluginCommands Registering 'help:commands'.
> Sat Nov 21 2015 14:06:18 GMT+0100 (CET) notice Tennu Loading your plugins
> Sat Nov 21 2015 14:06:18 GMT+0100 (CET) notice Tennu Client created.
> Sat Nov 21 2015 14:06:18 GMT+0100 (CET) notice Tennu Connected
> Sat Nov 21 2015 14:06:18 GMT+0100 (CET) info <- :ircd.local NOTICE Auth :*** Looking up your hostname...
> Sat Nov 21 2015 14:06:18 GMT+0100 (CET) info <- :ircd.local NOTICE Auth :*** Could not resolve your hostname: Domain name not found; using your IP address (10.0.0.2) instead.
> Sat Nov 21 2015 14:06:29 GMT+0100 (CET) notice Tennu Closing IRC Connection.
> Sat Nov 21 2015 14:06:29 GMT+0100 (CET) notice Tennu Disconnected
> Sat Nov 21 2015 14:06:29 GMT+0100 (CET) info <- ERROR :Closing link: (unknown@10.0.0.2) [Registration timeout]
> Sat Nov 21 2015 14:06:29 GMT+0100 (CET) error Client failed to connect because of: socketEnded

I'll have a closer look into the messages that I receive from InspIRCd and keep this ticket updated. :)

**Comment by tomhatzer** [comment]
InspIRCd needs to have the CAP module loaded, otherwise tennu won't send the username and user to the server.

Information from https://wiki.inspircd.org/Historical:Modules/2.1/cap
> This module implements the CAP capabilities extension as seen in many other IRC servers as a more sane replacement for PROTOCTL which can work before client registration. This module is required for STARTTLS support, SASL support, and adds extra facilities to other modules such as NAMESX.

Will see if I can get this implemented :)

**Comment by Havvy** [comment]
You can also use `"daemon": "irc2"` in your config. It'll disable the channel plugin though, but given that it sometimes throws (mostly harmless) errors, that's probably okay.
