### ISSUE TITLE
Notices?

### ISSUE THREAD

**Issue by ellisgl** [Tennu/tennu#71]
How do I listen for Notices?

I tried .on('notice', ....) but that got me nowhere.

**Comment by Havvy** [comment]
That should work. Do you have an example plugin?

**Comment by ellisgl** [comment]
Well I faked what I needed (just make a plugin to respond to a command to register with Nickserv). But was trying to trigger on NOTICE from the Nickserv so it would register it self.

**Comment by Havvy** [comment]
Without more information, I don't actually know the issue. Closing for now.
