### ISSUE TITLE
Help Enhancement

### ISSUE THREAD

**Issue by ellisgl** [Tennu/tennu#72]
It would be nice to be able to nice to add stuff to the main help plugin from plugins. Like the the  brief description of the command.

So if I type !help, I would get back:

```
======================
==       Help       ==
======================
!help: Display this.
!help {command}: Displays help for command.
!commands: displays available commands.
!dice: Rolls the dice.
!coin: Flips a coin.
```

**Comment by Havvy** [comment]
@ellisgl Can you join #heartless on irc.mibbit.net ? Alternatively, you could give me a channel to join.

I've some variations on this idea, but it'd be faster to discuss them over IRC than Github.

**Comment by VictorioBerra** [comment]
@ellisgl what did you end up doing?

**Comment by ellisgl** [comment]
I believe I hacked something together from another library. Which I guess I
deleted a while back ago. I haven't with that company in 3 years where I
was using it.

**Comment by VictorioBerra** [comment]
You were using Tennu professionally at work?

**Comment by ellisgl** [comment]
It was internally for like less than 20 people. And I think I ended up switching libs twice.
