### ISSUE TITLE
Multiple Networks

### ISSUE THREAD

**Issue by XdeadrushX** [Tennu/tennu#80]
How to multiple server connections at the same time..
 I want to have the client connected to multiple servers without writing the hole handling stuff all over again. Are there any ways to do so?

**Comment by VictorioBerra** [comment]
Unfortunately I think you will have to create your client instances in a loop. You could put your configuration in an array and iterate it. You could move that configuration into chunks and use the spread operator to include those chunks (like plugins, database connections, etc). Shouldnt be too hard.

**Comment by XdeadrushX** [comment]
Thanks, I'll see what I can do ...
